### ISSUE TITLE
I love this project!

### ISSUE THREAD

**Issue by nkasvosve** [juanpablo-santos/stripes-spring-boot#1]
Dude, nice work. I am huge fan of Stripes and glad to see you have brought it forward to work with Spring Boot. Nice work!

**Comment by juanpablo-santos** [comment]
Hi @nkasvosve, thanks for your nice comment :-) Ideally, I'd love to get this starter merged into Stripes' main distribution, and pinged their user ML about it, but so far there hasn't been much movement..
