### ISSUE TITLE
Consider adding Spring Boot 2 support

### ISSUE THREAD

**Issue by snicoll** [juanpablo-santos/stripes-spring-boot#4]
Relates to https://github.com/spring-projects/spring-boot/issues/13510

We are reviewing our [community starters list](https://github.com/spring-projects/spring-boot/blob/7683d346e31bbe0313a03ce487ee59454665a143/spring-boot-project/spring-boot-starters/README.adoc) and a quick look here suggests that this starter doesn’t yet support Spring Boot 2.

Can you please let us know if/when you plan to support Spring Boot 2?

Thanks!

**Comment by juanpablo-santos** [comment]
Hi @snicoll,

yes I plan to add support for it, although it may take a couple of weeks before I can look into it..

thanks for your interest on seeing this through!

br,
juan pablo

**Comment by juanpablo-santos** [comment]
Hi @snicoll,

latest master should support latest Spring Boot 2, would you mind taking a look at it to see if something else is needed? I'm planning on releasing master as is right now somewhere next week.

thx + br

**Comment by snicoll** [comment]
Sweet, thank you!
