### ISSUE TITLE
404 when launching jar

### ISSUE THREAD

**Issue by pieczkus** [juanpablo-santos/stripes-spring-boot#6]
Hello,

When launching your sample app as

`java -jar target/stripes-spring-boot-sample-2.3.4.jar`

and navigating to 

`localhost:8080/index.jsp`

I'm getting Spring generic error page. Please advise/

![Screenshot 2021-04-29 at 09 27 38](https://user-images.githubusercontent.com/3526014/116515897-31ab3d00-a8cd-11eb-8c3b-62ac4edabdc9.png)

**Comment by juanpablo-santos** [comment]
Hi @pieczkus !

thanks for your interest with this library :-) It seems that Spring Boot is unable to serve web resources from a fat jar unless they are packed inside a jar. OTOH, this doesn't happen if you run the application using `mvn spring-boot:run` which is weird, if it runs one way it should run the other, and if it doesn't run the first way, the second way also shouldn't.

Anyway, I'll push a fix in a minute, and while at it, I'll generate a new version using Spring Boot 2.3.10.RELEASE.

cheers,
juan pablo
